apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-app
  labels:
    app: kubernetes-test-app
spec:
  selector:
    app: kubernetes-test-app
  ports:
    - protocol: TCP
      port: 8080        # External port exposed by the service
      targetPort: 5000  # Internal container port your app listens on
  type: ClusterIP       # Internal service type (default); can be NodePort or LoadBalancer if needed